name: Test
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        ocaml-version: [ '4.12.0' ]
    steps:
      - uses: actions/checkout@v2
      - name: OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          dune-cache: ${{ matrix.operating-system == 'ubuntu-latest' }}
      - name: Install deps
        run: |
          opam pin add postgres.dev -n .
          opam pin add postgres-lwt.dev -n .
          opam pin add postgres-lwt-unix.dev -n  .
          opam pin add postgres-mirage.dev -n .
          opam install -t . --deps-only
      - name: Check build
        run: opam exec -- dune build @install
      - name: Run Test
        run: opam exec -- dune runtest
